CREATE DATABASE QLCH;
USE QLCH;
CREATE TABLE DON_HANG(
MaDonHang INT PRIMARY KEY,
MaKhachHang VARCHAR(30) NOT NULL,
NgayDat DATE NOT NULL,
TrangThai VARCHAR(20) NOT NULL
)

CREATE TABLE DON_HANG_CHI_TIET(
MaDonHangCT INT PRIMARY KEY,
MaDonHang INT NOT NULL,
MaSP INT NOT NULL,
SoLuong INT NOT NULL,
GiaBan INT NOT NULL
)

CREATE TABLE LOAI_SP(
MaLoai CHAR(6) PRIMARY KEY,
TenLoai VARCHAR(60)
)

CREATE TABLE SAN_PHAM(
MaSP CHAR (6) PRIMARY KEY,
TenSP VARCHAR (70) NOT NULL,
MoTa TEXT NOT NULL,
SoLuong INT NOT NULL,
DonGia FLOAT NOT NULL,
HinhAnh VARCHAR (255) NOT NULL,
NhaSX VARCHAR (255) NOT NULL,
MaLoai CHAR (6) NOT NULL
)

CREATE TABLE TAI_KHOAN(
ID VARCHAR (30) PRIMARY KEY,
Pass VARCHAR (30) NOT NULL,
VaiTro VARCHAR (30) NOT NULL,
HoTen VARCHAR (30) NOT NULL,
DiaChi VARCHAR (50) NOT NULL,
SoDT VARCHAR (11) NOT NULL,
Email VARCHAR (30) NOT NULL,

)

insert into TAI_KHOAN values ('Nghia','123','Admin',N'Tran Quoc Nghia','Quảng Ngãi','01202422733','nghia@gmail.com')
insert into TAI_KHOAN values ('Nghia1','123','User',N'Tran Quoc Nghia','Quảng Ngãi','01202422733','nghia@gmail.com')